all: p1testDriver p1testDriver2 p1testDriver3

p1testDriver: p1testDriver.c
	gcc -o p1testDriver p1testDriver.c
	
p1testDriver2: p1testDriver2.c
	gcc -o p1testDriver2 p1testDriver2.c
	
p1testDriver3: p1testDriver3.c
	gcc -o p1testDriver3 p1testDriver3.c
